// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBre_h3XS82Q8HYiIcvz6_rlZsiHw93RB4',
    appId: '1:790476190300:web:097b5285a8ad202fb86c99',
    messagingSenderId: '790476190300',
    projectId: 'pudim-perfeito',
    authDomain: 'pudim-perfeito.firebaseapp.com',
    databaseURL: 'https://pudim-perfeito-default-rtdb.firebaseio.com',
    storageBucket: 'pudim-perfeito.firebasestorage.app',
    measurementId: 'G-CB45EBHDQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvzt6HqsGyAM1Mcc4SQ8SYyjWvNUJnkSQ',
    appId: '1:790476190300:android:ecfbe0fc0a4c6e83b86c99',
    messagingSenderId: '790476190300',
    projectId: 'pudim-perfeito',
    databaseURL: 'https://pudim-perfeito-default-rtdb.firebaseio.com',
    storageBucket: 'pudim-perfeito.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmu9Vj08-FZatB4KSP2-iuCI-9Pj1x02w',
    appId: '1:790476190300:ios:7577c505fb0e1175b86c99',
    messagingSenderId: '790476190300',
    projectId: 'pudim-perfeito',
    databaseURL: 'https://pudim-perfeito-default-rtdb.firebaseio.com',
    storageBucket: 'pudim-perfeito.firebasestorage.app',
    iosBundleId: 'com.example.crmPudim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmu9Vj08-FZatB4KSP2-iuCI-9Pj1x02w',
    appId: '1:790476190300:ios:7577c505fb0e1175b86c99',
    messagingSenderId: '790476190300',
    projectId: 'pudim-perfeito',
    databaseURL: 'https://pudim-perfeito-default-rtdb.firebaseio.com',
    storageBucket: 'pudim-perfeito.firebasestorage.app',
    iosBundleId: 'com.example.crmPudim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBre_h3XS82Q8HYiIcvz6_rlZsiHw93RB4',
    appId: '1:790476190300:web:f29352c481a8f5cdb86c99',
    messagingSenderId: '790476190300',
    projectId: 'pudim-perfeito',
    authDomain: 'pudim-perfeito.firebaseapp.com',
    databaseURL: 'https://pudim-perfeito-default-rtdb.firebaseio.com',
    storageBucket: 'pudim-perfeito.firebasestorage.app',
    measurementId: 'G-9FGS7YVDVC',
  );
}
